# Generated by Django 3.2.7 on 2021-09-19 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_defaultagenecy'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='recorder_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
