# Generated by Django 3.2.7 on 2021-09-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0004_system_recorder_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('freq', models.IntegerField()),
                ('sysNum', models.IntegerField()),
                ('shortName', models.CharField(max_length=255)),
                ('talkgroup', models.IntegerField()),
                ('talkgrouptag', models.CharField(max_length=255)),
                ('elasped', models.IntegerField()),
                ('length', models.IntegerField()),
                ('state', models.IntegerField()),
                ('recNum', models.IntegerField()),
                ('srcNum', models.IntegerField()),
                ('recState', models.IntegerField()),
                ('sigmffilename', models.TextField()),
                ('debugfilename', models.TextField()),
                ('filename', models.TextField()),
                ('statusfilename', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('stopTime', models.DateTimeField()),
                ('phase2', models.BooleanField(default=False)),
                ('conventional', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=False)),
                ('emergency', models.BooleanField(default=False)),
                ('analog', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Freq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
                ('spikes', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('errors', models.IntegerField()),
                ('position', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('position', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('signal_system', models.CharField(max_length=50)),
                ('emergency', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoderate', models.IntegerField(blank=True, null=True)),
                ('activeCalls', models.ManyToManyField(to='telemetry.Call')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.system', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='freqList',
            field=models.ManyToManyField(to='telemetry.Freq'),
        ),
        migrations.AddField(
            model_name='call',
            name='sourceList',
            field=models.ManyToManyField(to='telemetry.Source'),
        ),
    ]
