# Generated by Django 3.2.7 on 2021-09-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='position',
        ),
        migrations.RemoveField(
            model_name='source',
            name='time',
        ),
    ]
