# Generated by Django 3.2.7 on 2021-09-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_auto_20210919_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freq',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='freq',
            name='length',
        ),
        migrations.RemoveField(
            model_name='freq',
            name='position',
        ),
        migrations.RemoveField(
            model_name='freq',
            name='spikes',
        ),
        migrations.RemoveField(
            model_name='freq',
            name='time',
        ),
    ]
